export enum EStorageKey {
  ACCOUNTS = "ACCOUNTS",
  THREADS_PROFILE = "THREADS_PROFILE",
  INSTAGRAM_PROFILE = "INSTAGRAM_PROFILE",
  FACEBOOK_PROFILE = "FACEBOOK_PROFILE",
  NOTIFY_LATEST_EXTENSION_VERSION = "NOTIFY_LATEST_EXTENSION_VERSION",
  THEME = "THEME"
}

export enum ESocialProvider {
  FACEBOOK = "FACEBOOK",
  INSTAGRAM = "INSTAGRAM",
  THREADS = "THREADS",
  X = "X"
}

export enum EDownloadSeperateType {
  FACEBOOK_POST = "FACEBOOK_POST",
  FACEBOOK_STORY = "FACEBOOK_STORY",
  FACEBOOK_VIDEO = "FACEBOOK_VIDEO",
  FACEBOOK_REEL = "FACEBOOK_REEL",
  FACEBOOK_COMMENT_VIDEO = "FACEBOOK_COMMENT_VIDEO",

  INSTAGRAM_POST = "INSTAGRAM_POST",
  INSTAGRAM_REEL = "INSTAGRAM_REEL",
  INSTAGRAM_HIGHLIGHT = "INSTAGRAM_HIGHLIGHT",

  THREADS_POST = "THREADS_POST",

  X_POST = "X_POST"
}

export enum ERemoteMessageType {
  RETRIEVE_X_ACCOUNT_CREDENTIALS = "RETRIEVE_X_ACCOUNT_CREDENTIALS"
}
